# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marulong/webserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marulong/webserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marulong/webserver/CMakeFiles /home/marulong/webserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marulong/webserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named webserver

# Build rule for target.
webserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 webserver
.PHONY : webserver

# fast build rule for target.
webserver/fast:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/build
.PHONY : webserver/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

examples/echo_server.o: examples/echo_server.cc.o

.PHONY : examples/echo_server.o

# target to build an object file
examples/echo_server.cc.o:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.o
.PHONY : examples/echo_server.cc.o

examples/echo_server.i: examples/echo_server.cc.i

.PHONY : examples/echo_server.i

# target to preprocess a source file
examples/echo_server.cc.i:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.i
.PHONY : examples/echo_server.cc.i

examples/echo_server.s: examples/echo_server.cc.s

.PHONY : examples/echo_server.s

# target to generate assembly for a file
examples/echo_server.cc.s:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.s
.PHONY : examples/echo_server.cc.s

tests/test_address.o: tests/test_address.cc.o

.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cc.o:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.o
.PHONY : tests/test_address.cc.o

tests/test_address.i: tests/test_address.cc.i

.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cc.i:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.i
.PHONY : tests/test_address.cc.i

tests/test_address.s: tests/test_address.cc.s

.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cc.s:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.s
.PHONY : tests/test_address.cc.s

tests/test_bytearray.o: tests/test_bytearray.cc.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cc.o:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.o
.PHONY : tests/test_bytearray.cc.o

tests/test_bytearray.i: tests/test_bytearray.cc.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cc.i:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.i
.PHONY : tests/test_bytearray.cc.i

tests/test_bytearray.s: tests/test_bytearray.cc.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cc.s:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.s
.PHONY : tests/test_bytearray.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_connection.o: tests/test_connection.cc.o

.PHONY : tests/test_connection.o

# target to build an object file
tests/test_connection.cc.o:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_connection.cc.o
.PHONY : tests/test_connection.cc.o

tests/test_connection.i: tests/test_connection.cc.i

.PHONY : tests/test_connection.i

# target to preprocess a source file
tests/test_connection.cc.i:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_connection.cc.i
.PHONY : tests/test_connection.cc.i

tests/test_connection.s: tests/test_connection.cc.s

.PHONY : tests/test_connection.s

# target to generate assembly for a file
tests/test_connection.cc.s:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_connection.cc.s
.PHONY : tests/test_connection.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_hook.o: tests/test_hook.cc.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cc.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.o
.PHONY : tests/test_hook.cc.o

tests/test_hook.i: tests/test_hook.cc.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cc.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.i
.PHONY : tests/test_hook.cc.i

tests/test_hook.s: tests/test_hook.cc.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cc.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.s
.PHONY : tests/test_hook.cc.s

tests/test_http.o: tests/test_http.cc.o

.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cc.o:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.o
.PHONY : tests/test_http.cc.o

tests/test_http.i: tests/test_http.cc.i

.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cc.i:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.i
.PHONY : tests/test_http.cc.i

tests/test_http.s: tests/test_http.cc.s

.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cc.s:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.s
.PHONY : tests/test_http.cc.s

tests/test_http_parser.o: tests/test_http_parser.cc.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cc.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.o
.PHONY : tests/test_http_parser.cc.o

tests/test_http_parser.i: tests/test_http_parser.cc.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cc.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.i
.PHONY : tests/test_http_parser.cc.i

tests/test_http_parser.s: tests/test_http_parser.cc.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cc.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.s
.PHONY : tests/test_http_parser.cc.s

tests/test_http_server.o: tests/test_http_server.cc.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cc.o:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.o
.PHONY : tests/test_http_server.cc.o

tests/test_http_server.i: tests/test_http_server.cc.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cc.i:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.i
.PHONY : tests/test_http_server.cc.i

tests/test_http_server.s: tests/test_http_server.cc.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cc.s:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.s
.PHONY : tests/test_http_server.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_socket.o: tests/test_socket.cc.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cc.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.o
.PHONY : tests/test_socket.cc.o

tests/test_socket.i: tests/test_socket.cc.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cc.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.i
.PHONY : tests/test_socket.cc.i

tests/test_socket.s: tests/test_socket.cc.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cc.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.s
.PHONY : tests/test_socket.cc.s

tests/test_tcp_server.o: tests/test_tcp_server.cc.o

.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.o
.PHONY : tests/test_tcp_server.cc.o

tests/test_tcp_server.i: tests/test_tcp_server.cc.i

.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.i
.PHONY : tests/test_tcp_server.cc.i

tests/test_tcp_server.s: tests/test_tcp_server.cc.s

.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.s
.PHONY : tests/test_tcp_server.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

webserver/coroutine.o: webserver/coroutine.cc.o

.PHONY : webserver/coroutine.o

# target to build an object file
webserver/coroutine.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/coroutine.cc.o
.PHONY : webserver/coroutine.cc.o

webserver/coroutine.i: webserver/coroutine.cc.i

.PHONY : webserver/coroutine.i

# target to preprocess a source file
webserver/coroutine.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/coroutine.cc.i
.PHONY : webserver/coroutine.cc.i

webserver/coroutine.s: webserver/coroutine.cc.s

.PHONY : webserver/coroutine.s

# target to generate assembly for a file
webserver/coroutine.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/coroutine.cc.s
.PHONY : webserver/coroutine.cc.s

webserver/coroutinescheduler.o: webserver/coroutinescheduler.cc.o

.PHONY : webserver/coroutinescheduler.o

# target to build an object file
webserver/coroutinescheduler.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/coroutinescheduler.cc.o
.PHONY : webserver/coroutinescheduler.cc.o

webserver/coroutinescheduler.i: webserver/coroutinescheduler.cc.i

.PHONY : webserver/coroutinescheduler.i

# target to preprocess a source file
webserver/coroutinescheduler.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/coroutinescheduler.cc.i
.PHONY : webserver/coroutinescheduler.cc.i

webserver/coroutinescheduler.s: webserver/coroutinescheduler.cc.s

.PHONY : webserver/coroutinescheduler.s

# target to generate assembly for a file
webserver/coroutinescheduler.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/coroutinescheduler.cc.s
.PHONY : webserver/coroutinescheduler.cc.s

webserver/fd_manager.o: webserver/fd_manager.cc.o

.PHONY : webserver/fd_manager.o

# target to build an object file
webserver/fd_manager.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/fd_manager.cc.o
.PHONY : webserver/fd_manager.cc.o

webserver/fd_manager.i: webserver/fd_manager.cc.i

.PHONY : webserver/fd_manager.i

# target to preprocess a source file
webserver/fd_manager.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/fd_manager.cc.i
.PHONY : webserver/fd_manager.cc.i

webserver/fd_manager.s: webserver/fd_manager.cc.s

.PHONY : webserver/fd_manager.s

# target to generate assembly for a file
webserver/fd_manager.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/fd_manager.cc.s
.PHONY : webserver/fd_manager.cc.s

webserver/fileconfig.o: webserver/fileconfig.cc.o

.PHONY : webserver/fileconfig.o

# target to build an object file
webserver/fileconfig.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/fileconfig.cc.o
.PHONY : webserver/fileconfig.cc.o

webserver/fileconfig.i: webserver/fileconfig.cc.i

.PHONY : webserver/fileconfig.i

# target to preprocess a source file
webserver/fileconfig.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/fileconfig.cc.i
.PHONY : webserver/fileconfig.cc.i

webserver/fileconfig.s: webserver/fileconfig.cc.s

.PHONY : webserver/fileconfig.s

# target to generate assembly for a file
webserver/fileconfig.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/fileconfig.cc.s
.PHONY : webserver/fileconfig.cc.s

webserver/filestream.o: webserver/filestream.cc.o

.PHONY : webserver/filestream.o

# target to build an object file
webserver/filestream.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/filestream.cc.o
.PHONY : webserver/filestream.cc.o

webserver/filestream.i: webserver/filestream.cc.i

.PHONY : webserver/filestream.i

# target to preprocess a source file
webserver/filestream.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/filestream.cc.i
.PHONY : webserver/filestream.cc.i

webserver/filestream.s: webserver/filestream.cc.s

.PHONY : webserver/filestream.s

# target to generate assembly for a file
webserver/filestream.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/filestream.cc.s
.PHONY : webserver/filestream.cc.s

webserver/hook.o: webserver/hook.cc.o

.PHONY : webserver/hook.o

# target to build an object file
webserver/hook.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/hook.cc.o
.PHONY : webserver/hook.cc.o

webserver/hook.i: webserver/hook.cc.i

.PHONY : webserver/hook.i

# target to preprocess a source file
webserver/hook.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/hook.cc.i
.PHONY : webserver/hook.cc.i

webserver/hook.s: webserver/hook.cc.s

.PHONY : webserver/hook.s

# target to generate assembly for a file
webserver/hook.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/hook.cc.s
.PHONY : webserver/hook.cc.s

webserver/http/http.o: webserver/http/http.cc.o

.PHONY : webserver/http/http.o

# target to build an object file
webserver/http/http.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http.cc.o
.PHONY : webserver/http/http.cc.o

webserver/http/http.i: webserver/http/http.cc.i

.PHONY : webserver/http/http.i

# target to preprocess a source file
webserver/http/http.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http.cc.i
.PHONY : webserver/http/http.cc.i

webserver/http/http.s: webserver/http/http.cc.s

.PHONY : webserver/http/http.s

# target to generate assembly for a file
webserver/http/http.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http.cc.s
.PHONY : webserver/http/http.cc.s

webserver/http/http11_parser.o: webserver/http/http11_parser.cc.o

.PHONY : webserver/http/http11_parser.o

# target to build an object file
webserver/http/http11_parser.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http11_parser.cc.o
.PHONY : webserver/http/http11_parser.cc.o

webserver/http/http11_parser.i: webserver/http/http11_parser.cc.i

.PHONY : webserver/http/http11_parser.i

# target to preprocess a source file
webserver/http/http11_parser.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http11_parser.cc.i
.PHONY : webserver/http/http11_parser.cc.i

webserver/http/http11_parser.s: webserver/http/http11_parser.cc.s

.PHONY : webserver/http/http11_parser.s

# target to generate assembly for a file
webserver/http/http11_parser.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http11_parser.cc.s
.PHONY : webserver/http/http11_parser.cc.s

webserver/http/http_connection.o: webserver/http/http_connection.cc.o

.PHONY : webserver/http/http_connection.o

# target to build an object file
webserver/http/http_connection.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_connection.cc.o
.PHONY : webserver/http/http_connection.cc.o

webserver/http/http_connection.i: webserver/http/http_connection.cc.i

.PHONY : webserver/http/http_connection.i

# target to preprocess a source file
webserver/http/http_connection.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_connection.cc.i
.PHONY : webserver/http/http_connection.cc.i

webserver/http/http_connection.s: webserver/http/http_connection.cc.s

.PHONY : webserver/http/http_connection.s

# target to generate assembly for a file
webserver/http/http_connection.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_connection.cc.s
.PHONY : webserver/http/http_connection.cc.s

webserver/http/http_parser.o: webserver/http/http_parser.cc.o

.PHONY : webserver/http/http_parser.o

# target to build an object file
webserver/http/http_parser.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_parser.cc.o
.PHONY : webserver/http/http_parser.cc.o

webserver/http/http_parser.i: webserver/http/http_parser.cc.i

.PHONY : webserver/http/http_parser.i

# target to preprocess a source file
webserver/http/http_parser.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_parser.cc.i
.PHONY : webserver/http/http_parser.cc.i

webserver/http/http_parser.s: webserver/http/http_parser.cc.s

.PHONY : webserver/http/http_parser.s

# target to generate assembly for a file
webserver/http/http_parser.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_parser.cc.s
.PHONY : webserver/http/http_parser.cc.s

webserver/http/http_server.o: webserver/http/http_server.cc.o

.PHONY : webserver/http/http_server.o

# target to build an object file
webserver/http/http_server.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_server.cc.o
.PHONY : webserver/http/http_server.cc.o

webserver/http/http_server.i: webserver/http/http_server.cc.i

.PHONY : webserver/http/http_server.i

# target to preprocess a source file
webserver/http/http_server.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_server.cc.i
.PHONY : webserver/http/http_server.cc.i

webserver/http/http_server.s: webserver/http/http_server.cc.s

.PHONY : webserver/http/http_server.s

# target to generate assembly for a file
webserver/http/http_server.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_server.cc.s
.PHONY : webserver/http/http_server.cc.s

webserver/http/http_session.o: webserver/http/http_session.cc.o

.PHONY : webserver/http/http_session.o

# target to build an object file
webserver/http/http_session.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_session.cc.o
.PHONY : webserver/http/http_session.cc.o

webserver/http/http_session.i: webserver/http/http_session.cc.i

.PHONY : webserver/http/http_session.i

# target to preprocess a source file
webserver/http/http_session.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_session.cc.i
.PHONY : webserver/http/http_session.cc.i

webserver/http/http_session.s: webserver/http/http_session.cc.s

.PHONY : webserver/http/http_session.s

# target to generate assembly for a file
webserver/http/http_session.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/http_session.cc.s
.PHONY : webserver/http/http_session.cc.s

webserver/http/httpclient_parser.o: webserver/http/httpclient_parser.cc.o

.PHONY : webserver/http/httpclient_parser.o

# target to build an object file
webserver/http/httpclient_parser.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/httpclient_parser.cc.o
.PHONY : webserver/http/httpclient_parser.cc.o

webserver/http/httpclient_parser.i: webserver/http/httpclient_parser.cc.i

.PHONY : webserver/http/httpclient_parser.i

# target to preprocess a source file
webserver/http/httpclient_parser.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/httpclient_parser.cc.i
.PHONY : webserver/http/httpclient_parser.cc.i

webserver/http/httpclient_parser.s: webserver/http/httpclient_parser.cc.s

.PHONY : webserver/http/httpclient_parser.s

# target to generate assembly for a file
webserver/http/httpclient_parser.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/httpclient_parser.cc.s
.PHONY : webserver/http/httpclient_parser.cc.s

webserver/http/servlet.o: webserver/http/servlet.cc.o

.PHONY : webserver/http/servlet.o

# target to build an object file
webserver/http/servlet.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/servlet.cc.o
.PHONY : webserver/http/servlet.cc.o

webserver/http/servlet.i: webserver/http/servlet.cc.i

.PHONY : webserver/http/servlet.i

# target to preprocess a source file
webserver/http/servlet.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/servlet.cc.i
.PHONY : webserver/http/servlet.cc.i

webserver/http/servlet.s: webserver/http/servlet.cc.s

.PHONY : webserver/http/servlet.s

# target to generate assembly for a file
webserver/http/servlet.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/http/servlet.cc.s
.PHONY : webserver/http/servlet.cc.s

webserver/iobytearray.o: webserver/iobytearray.cc.o

.PHONY : webserver/iobytearray.o

# target to build an object file
webserver/iobytearray.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/iobytearray.cc.o
.PHONY : webserver/iobytearray.cc.o

webserver/iobytearray.i: webserver/iobytearray.cc.i

.PHONY : webserver/iobytearray.i

# target to preprocess a source file
webserver/iobytearray.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/iobytearray.cc.i
.PHONY : webserver/iobytearray.cc.i

webserver/iobytearray.s: webserver/iobytearray.cc.s

.PHONY : webserver/iobytearray.s

# target to generate assembly for a file
webserver/iobytearray.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/iobytearray.cc.s
.PHONY : webserver/iobytearray.cc.s

webserver/iomanager.o: webserver/iomanager.cc.o

.PHONY : webserver/iomanager.o

# target to build an object file
webserver/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/iomanager.cc.o
.PHONY : webserver/iomanager.cc.o

webserver/iomanager.i: webserver/iomanager.cc.i

.PHONY : webserver/iomanager.i

# target to preprocess a source file
webserver/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/iomanager.cc.i
.PHONY : webserver/iomanager.cc.i

webserver/iomanager.s: webserver/iomanager.cc.s

.PHONY : webserver/iomanager.s

# target to generate assembly for a file
webserver/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/iomanager.cc.s
.PHONY : webserver/iomanager.cc.s

webserver/log.o: webserver/log.cc.o

.PHONY : webserver/log.o

# target to build an object file
webserver/log.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/log.cc.o
.PHONY : webserver/log.cc.o

webserver/log.i: webserver/log.cc.i

.PHONY : webserver/log.i

# target to preprocess a source file
webserver/log.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/log.cc.i
.PHONY : webserver/log.cc.i

webserver/log.s: webserver/log.cc.s

.PHONY : webserver/log.s

# target to generate assembly for a file
webserver/log.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/log.cc.s
.PHONY : webserver/log.cc.s

webserver/sockaddr.o: webserver/sockaddr.cc.o

.PHONY : webserver/sockaddr.o

# target to build an object file
webserver/sockaddr.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/sockaddr.cc.o
.PHONY : webserver/sockaddr.cc.o

webserver/sockaddr.i: webserver/sockaddr.cc.i

.PHONY : webserver/sockaddr.i

# target to preprocess a source file
webserver/sockaddr.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/sockaddr.cc.i
.PHONY : webserver/sockaddr.cc.i

webserver/sockaddr.s: webserver/sockaddr.cc.s

.PHONY : webserver/sockaddr.s

# target to generate assembly for a file
webserver/sockaddr.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/sockaddr.cc.s
.PHONY : webserver/sockaddr.cc.s

webserver/socket.o: webserver/socket.cc.o

.PHONY : webserver/socket.o

# target to build an object file
webserver/socket.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/socket.cc.o
.PHONY : webserver/socket.cc.o

webserver/socket.i: webserver/socket.cc.i

.PHONY : webserver/socket.i

# target to preprocess a source file
webserver/socket.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/socket.cc.i
.PHONY : webserver/socket.cc.i

webserver/socket.s: webserver/socket.cc.s

.PHONY : webserver/socket.s

# target to generate assembly for a file
webserver/socket.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/socket.cc.s
.PHONY : webserver/socket.cc.s

webserver/socket_stream.o: webserver/socket_stream.cc.o

.PHONY : webserver/socket_stream.o

# target to build an object file
webserver/socket_stream.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/socket_stream.cc.o
.PHONY : webserver/socket_stream.cc.o

webserver/socket_stream.i: webserver/socket_stream.cc.i

.PHONY : webserver/socket_stream.i

# target to preprocess a source file
webserver/socket_stream.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/socket_stream.cc.i
.PHONY : webserver/socket_stream.cc.i

webserver/socket_stream.s: webserver/socket_stream.cc.s

.PHONY : webserver/socket_stream.s

# target to generate assembly for a file
webserver/socket_stream.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/socket_stream.cc.s
.PHONY : webserver/socket_stream.cc.s

webserver/tcp_server.o: webserver/tcp_server.cc.o

.PHONY : webserver/tcp_server.o

# target to build an object file
webserver/tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/tcp_server.cc.o
.PHONY : webserver/tcp_server.cc.o

webserver/tcp_server.i: webserver/tcp_server.cc.i

.PHONY : webserver/tcp_server.i

# target to preprocess a source file
webserver/tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/tcp_server.cc.i
.PHONY : webserver/tcp_server.cc.i

webserver/tcp_server.s: webserver/tcp_server.cc.s

.PHONY : webserver/tcp_server.s

# target to generate assembly for a file
webserver/tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/tcp_server.cc.s
.PHONY : webserver/tcp_server.cc.s

webserver/thread.o: webserver/thread.cc.o

.PHONY : webserver/thread.o

# target to build an object file
webserver/thread.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/thread.cc.o
.PHONY : webserver/thread.cc.o

webserver/thread.i: webserver/thread.cc.i

.PHONY : webserver/thread.i

# target to preprocess a source file
webserver/thread.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/thread.cc.i
.PHONY : webserver/thread.cc.i

webserver/thread.s: webserver/thread.cc.s

.PHONY : webserver/thread.s

# target to generate assembly for a file
webserver/thread.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/thread.cc.s
.PHONY : webserver/thread.cc.s

webserver/timer.o: webserver/timer.cc.o

.PHONY : webserver/timer.o

# target to build an object file
webserver/timer.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/timer.cc.o
.PHONY : webserver/timer.cc.o

webserver/timer.i: webserver/timer.cc.i

.PHONY : webserver/timer.i

# target to preprocess a source file
webserver/timer.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/timer.cc.i
.PHONY : webserver/timer.cc.i

webserver/timer.s: webserver/timer.cc.s

.PHONY : webserver/timer.s

# target to generate assembly for a file
webserver/timer.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/timer.cc.s
.PHONY : webserver/timer.cc.s

webserver/util.o: webserver/util.cc.o

.PHONY : webserver/util.o

# target to build an object file
webserver/util.cc.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/util.cc.o
.PHONY : webserver/util.cc.o

webserver/util.i: webserver/util.cc.i

.PHONY : webserver/util.i

# target to preprocess a source file
webserver/util.cc.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/util.cc.i
.PHONY : webserver/util.cc.i

webserver/util.s: webserver/util.cc.s

.PHONY : webserver/util.s

# target to generate assembly for a file
webserver/util.cc.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver/util.cc.s
.PHONY : webserver/util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_http_connection"
	@echo "... test_fiber"
	@echo "... test_socket"
	@echo "... edit_cache"
	@echo "... test_util"
	@echo "... test_thread"
	@echo "... test_scheduler"
	@echo "... test_bytearray"
	@echo "... webserver"
	@echo "... test_config"
	@echo "... test_iomanager"
	@echo "... test_hook"
	@echo "... test_address"
	@echo "... test_tcp_server"
	@echo "... test_http"
	@echo "... test_http_parser"
	@echo "... echo_server"
	@echo "... test_http_server"
	@echo "... examples/echo_server.o"
	@echo "... examples/echo_server.i"
	@echo "... examples/echo_server.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_connection.o"
	@echo "... tests/test_connection.i"
	@echo "... tests/test_connection.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
	@echo "... webserver/coroutine.o"
	@echo "... webserver/coroutine.i"
	@echo "... webserver/coroutine.s"
	@echo "... webserver/coroutinescheduler.o"
	@echo "... webserver/coroutinescheduler.i"
	@echo "... webserver/coroutinescheduler.s"
	@echo "... webserver/fd_manager.o"
	@echo "... webserver/fd_manager.i"
	@echo "... webserver/fd_manager.s"
	@echo "... webserver/fileconfig.o"
	@echo "... webserver/fileconfig.i"
	@echo "... webserver/fileconfig.s"
	@echo "... webserver/filestream.o"
	@echo "... webserver/filestream.i"
	@echo "... webserver/filestream.s"
	@echo "... webserver/hook.o"
	@echo "... webserver/hook.i"
	@echo "... webserver/hook.s"
	@echo "... webserver/http/http.o"
	@echo "... webserver/http/http.i"
	@echo "... webserver/http/http.s"
	@echo "... webserver/http/http11_parser.o"
	@echo "... webserver/http/http11_parser.i"
	@echo "... webserver/http/http11_parser.s"
	@echo "... webserver/http/http_connection.o"
	@echo "... webserver/http/http_connection.i"
	@echo "... webserver/http/http_connection.s"
	@echo "... webserver/http/http_parser.o"
	@echo "... webserver/http/http_parser.i"
	@echo "... webserver/http/http_parser.s"
	@echo "... webserver/http/http_server.o"
	@echo "... webserver/http/http_server.i"
	@echo "... webserver/http/http_server.s"
	@echo "... webserver/http/http_session.o"
	@echo "... webserver/http/http_session.i"
	@echo "... webserver/http/http_session.s"
	@echo "... webserver/http/httpclient_parser.o"
	@echo "... webserver/http/httpclient_parser.i"
	@echo "... webserver/http/httpclient_parser.s"
	@echo "... webserver/http/servlet.o"
	@echo "... webserver/http/servlet.i"
	@echo "... webserver/http/servlet.s"
	@echo "... webserver/iobytearray.o"
	@echo "... webserver/iobytearray.i"
	@echo "... webserver/iobytearray.s"
	@echo "... webserver/iomanager.o"
	@echo "... webserver/iomanager.i"
	@echo "... webserver/iomanager.s"
	@echo "... webserver/log.o"
	@echo "... webserver/log.i"
	@echo "... webserver/log.s"
	@echo "... webserver/sockaddr.o"
	@echo "... webserver/sockaddr.i"
	@echo "... webserver/sockaddr.s"
	@echo "... webserver/socket.o"
	@echo "... webserver/socket.i"
	@echo "... webserver/socket.s"
	@echo "... webserver/socket_stream.o"
	@echo "... webserver/socket_stream.i"
	@echo "... webserver/socket_stream.s"
	@echo "... webserver/tcp_server.o"
	@echo "... webserver/tcp_server.i"
	@echo "... webserver/tcp_server.s"
	@echo "... webserver/thread.o"
	@echo "... webserver/thread.i"
	@echo "... webserver/thread.s"
	@echo "... webserver/timer.o"
	@echo "... webserver/timer.i"
	@echo "... webserver/timer.s"
	@echo "... webserver/util.o"
	@echo "... webserver/util.i"
	@echo "... webserver/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

